name: Notice Github Repository Tags
on:
  push:
  schedule:
    - cron: '0 15 * * *'
jobs:
  notice:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ./go.mod
      - name: Notice Golang Tags
        run: go run main.go --owner golang --repository go
      - name: Notice Golang CI Lint Tags
        run: go run main.go --owner golangci --repository golangci-lint
      - name: Set up Git Config
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
      - name: Git Push
        run: |
          if (git diff --shortstat | grep '[0-9]'); then \
            git add *.csv; \
            git commit -m "update csv"; \
            git push origin HEAD:${GITHUB_REF}; \
          fi
